services:
  servicio_a:
    build: ./servicio_a
    container_name: calculadora-servicio-a
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db-actividades.cfsiu7tgzbib.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=12345678
      - DB_NAME=db-actividades
      - NOTIF_URL=http://servicio_b:5001/notificar
    networks:
      - red_interna

  servicio_b:
    build: ./servicio_b
    container_name: calculadora-servicio-b
    environment:
      - DB_HOST=db-actividades.cfsiu7tgzbib.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=12345678
      - DB_NAME=db-actividades
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge
